#-------------------------------
# General Site Settings
title: InSciM Project
logo: InscimLogoNew.png # You can add own logo.
description: This is Project InSciM website 

#-------------------------------
# Author Settings
author:
  name: PKN
  image: cover.png
  say-hello: Welcome to <strong>InSciM Official Home Page</strong>.
  bio: InSciM is a project concerning Modeling Uncertainty in Science (InSciM), funded by <a href="https://anr.fr/Projet-ANR-21-CE38-0003">French ANR JCJC 2021 - 2025, ANR-21-CE38-0003-01</a>.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Admin # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
